In [6]:
import pandas as pd
df = pd.read_json ("data/Accommodations.json",lines=True)
df.describe()

,beds,latitude,longitude,postal-code,rooms,toilets,suites,breakfast,verified
count,38280.000000,5.506100e+04,5.506100e+04,68228.000000,36982.000000,20854.000000,9736.000000,9734.0,12.0
mean,30.951698,1.665378e+04,3.305475e+03,30974.365114,15.995809,6.538794,0.731615,1.0,1.0
std,79.134620,5.451332e+05,1.324939e+05,25156.011576,38.202621,19.548513,6.166128,0.0,0.0
min,0.000000,-1.947924e+00,-1.016322e+02,0.000000,0.000000,0.000000,0.000000,1.0,1.0
25%,4.000000,0.000000e+00,0.000000e+00,6034.000000,2.000000,0.000000,0.000000,1.0,1.0
50%,9.000000,4.307927e+01,9.295483e+00,30028.000000,4.000000,1.000000,0.000000,1.0,1.0
75%,25.000000,4.492547e+01,1.249042e+01,47831.000000,14.000000,5.000000,0.000000,1.0,1.0
max,2600.000000,4.493033e+07,1.208115e+07,95973.000000,1093.000000,457.000000,212.000000,1.0,1.0

In [7]:
df.shape

(82645, 44)

In [13]:
count_null = df.isnull().sum()

In [11]:
n = df.shape[0]

In [16]:
perc_not_null = (n- count_null)/n*100
perc_not_null

_id                   100.000000
name                  100.000000
description            80.243209
number of stars        60.704217
address                97.769980
telephone              84.138181
cellular phone          8.830540
fax                    65.057777
web site               84.144231
email                  84.080102
opening period         14.999093
beds                   46.318592
region                100.000000
country                97.559441
latitude               66.623510
longitude              66.623510
postal-code            82.555509
city                   98.411277
province               53.565249
locality               42.908827
telephone2             10.926251
hamlet                 16.847964
rooms                  44.748019
toilets                25.233226
facilities             33.762478
credit/debit cards     12.672273
location               26.086273
languages              26.100793
sports equipment       15.099522
category               11.792607
suites                 11.780507
breakfast              11.778087
congress halls         11.778087
verified                0.014520
manager                 8.763991
elevation               4.850868
chain                   2.401839
high season price       7.661686
low season price        7.661686
photo                   7.672575
enrichment             20.831266
facebook                0.007260
instagram               0.002420
twitter                 0.001210
dtype: float64

In [23]:
count_null = df.groupby(by='region').sum()

,beds,latitude,longitude,postal-code,rooms,toilets,suites,breakfast,verified
region,,,,,,,,,
Basilicata,41671.0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0
Bretagne,0.0,9.585682e+02,-5.792001e+01,936500.0,0.0,0.0,0.0,0.0,0.0
Comunidad Foral de Navarra,0.0,7.673690e+04,9.701726e+03,0.0,0.0,0.0,0.0,0.0,0.0
Emilia Romagna,0.0,3.117281e+08,7.799191e+07,419062262.0,0.0,0.0,0.0,0.0,0.0
Friuli Venezia Giulia,39784.0,3.357888e+04,9.647721e+03,24310335.0,19226.0,19248.0,0.0,0.0,0.0
Ile-de-France,0.0,9.731438e+04,4.668476e+03,161102600.0,138962.0,0.0,0.0,0.0,0.0
Lazio,167835.0,1.122066e+05,3.342821e+04,0.0,83427.0,0.0,0.0,0.0,0.0
Liguria,61830.0,0.000000e+00,0.000000e+00,22774441.0,33642.0,0.0,0.0,0.0,0.0
Lombardia,367594.0,3.713001e+05,7.886304e+04,233955218.0,140975.0,1296.0,7123.0,9734.0,1.0
Marche,0.0,1.515988e+05,4.641391e+04,323084973.0,0.0,0.0,0.0,0.0,0.0
Pays de la Loire,0.0,3.711068e+04,-8.852965e+02,46945827.0,0.0,0.0,0.0,0.0,0.0
Piemonte,115340.0,0.000000e+00,0.000000e+00,32357617.0,0.0,0.0,0.0,0.0,0.0
Provence-Alpes-Côte d Azur,0.0,8.686658e+04,1.287823e+04,69970377.0,0.0,0.0,0.0,0.0,0.0
Puglia,209555.0,2.516098e+05,1.065420e+05,387162940.0,94738.0,80023.0,0.0,0.0,0.0
Región de Murcia,0.0,6.037587e+08,1.037062e+08,4978995.0,0.0,0.0,0.0,0.0,0.0
Toscana,0.0,2.546550e+05,1.453627e+02,563205.0,15.0,0.0,0.0,0.0,11.0
Trentino-Alto Adige,92654.0,4.606926e+02,1.102613e+02,57604040.0,45262.0,0.0,0.0,0.0,0.0
Umbria,88568.0,6.567169e+03,1.905415e+03,23764091.0,35310.0,35793.0,0.0,0.0,0.0
Veneto,0.0,5.828251e+03,1.306064e+03,304745562.0,0.0,0.0,0.0,0.0,0.0

In [29]:
regions = df.region.unique()
regions

array(['Basilicata', 'Bretagne', 'Comunidad Foral de Navarra',
       'Emilia Romagna', 'Friuli Venezia Giulia', 'Ile-de-France',
       'Liguria', 'Lombardia', 'Marche', 'Pays de la Loire', 'Piemonte',
       'Provence-Alpes-Côte d Azur', 'Puglia', 'Región de Murcia',
       'Lazio', 'Toscana', 'Trentino-Alto Adige', 'Umbria', 'Veneto'],
      dtype=object)

In [40]:
columns = df.columns
columns

Index(['_id', 'name', 'description', 'number of stars', 'address', 'telephone',
       'cellular phone', 'fax', 'web site', 'email', 'opening period', 'beds',
       'region', 'country', 'latitude', 'longitude', 'postal-code', 'city',
       'province', 'locality', 'telephone2', 'hamlet', 'rooms', 'toilets',
       'facilities', 'credit/debit cards', 'location', 'languages',
       'sports equipment', 'category', 'suites', 'breakfast', 'congress halls',
       'verified', 'manager', 'elevation', 'chain', 'high season price',
       'low season price', 'photo', 'enrichment', 'facebook', 'instagram',
       'twitter'],
      dtype='object')

In [81]:
def statistics(df, ctype,country=False):
    y = []
    values = df[ctype].unique()
    columns = df.columns
    for value in values:
        dr = df[df[ctype] == value]
        count_null = dr.isnull().sum()
        n = dr.shape[0]
        perc_not_null = (n- count_null)/n*100
        row = {}
        for i in range(0,len(perc_not_null)):
            row[columns[i]] = perc_not_null[i]
        row[ctype] = value
        y.append(row)
    names = y[0].keys()
    fn = 'data/' + ctype + '.csv'
    if country and not country != 'nan':
        print(country)
        print(ctype)
        fn = 'data/' + ctype + '-' + country + '.csv'
    with open(fn, 'w') as output_file:
        dict_writer = csv.DictWriter(output_file, names)
        dict_writer.writeheader()
        dict_writer.writerows(y)

In [82]:
import csv

types = ['region', 'country']
y = statistics(df, 'country')
countries = df['country'].unique()
for country in countries:
    dr = df.where(df['country'] == country)
    y = statistics(dr, 'region', country)

In [58]:
for country in countries:
    print(df['region'].where(df['country'] == country).unique())

['Basilicata' nan 'Emilia Romagna' 'Friuli Venezia Giulia' 'Liguria'
 'Lombardia' 'Marche' 'Puglia' 'Lazio' 'Toscana' 'Trentino-Alto Adige'
 'Umbria' 'Veneto']
[nan 'Bretagne' 'Ile-de-France' 'Pays de la Loire'
 'Provence-Alpes-Côte d Azur']
[nan 'Comunidad Foral de Navarra' 'Región de Murcia']
[nan]